AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Infra_as_a_code/Lambda
      Handler: func.lambda_handler  # Adjust your_handler_function accordingly
      Runtime: python3.12
      

