AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./Infra_as_a_code/Lambda
      Handler: func.your_handler_function  # Adjust your_handler_function accordingly
      Runtime: python3.12
      # Add the following line to specify the S3 bucket
      S3Bucket: antznette.datacraftedsolutions.com

