name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
        

      - name: Install SAM CLI
        run: |
          curl -Lf https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o sam.zip
          unzip sam.zip -d /usr/local/bin

      - name: Install pytest
        run: |
          pip install pytest


      - name: Run tests
        run: pytest tests/tests.py


      - name: Check for Changes
        run: |
          if [[ $(git diff --name-only ${{ github.sha }}) ]]; then
            echo "Changes detected, proceeding with deployment."
          else
            echo "No changes detected. Skipping deployment."
            exit 0
          fi  

      - name: SAM Deploy
        run: sam deploy --stack-name tonette-resume-stack --region us-east-1 --capabilities CAPABILITY_IAM --s3-bucket antznette.datacraftedsolutions.com --no-fail-on-empty-changeset
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
